### ISSUE TITLE
memory leak 

### ISSUE THREAD

**Issue by ignazioc** [jwhitehorn/SKDatabase#1]
i performed a profile with xcode and instrument wanting me about a memory leak in this row of code
[code]
result = [NSString stringWithUTF8String:(char *)sqlite3_column_text(statement,i)];
[code]

**Comment by jwhitehorn** [comment]
Thanks for the bug report!

I too have noticed some memory leaks with this. I have fixed some, but not all, with a patch I've recently committed. See https://github.com/jwhitehorn/SKDatabase/commit/0bab46126f38be6d2da54c77ec68a9aaf79f1d4d

Let me know if you have any success with that. Again, I am still seeing some leaks though, and I am stil trying to track them al down.
